[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt && python init_spacy.py"

[deploy]
startCommand = "gunicorn app:app"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicy = "on-failure"
maxRetries = 10 
